version: "3.9"

services:
  thumbnails-parser:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: thumbnail-parser
    networks:
      - thumbnailnw
    ports:
      - 8080:8080 # REST
      - 8082:8082 # gRPC
    volumes:
      - ./config.yml:/root/config.yml


networks:
  thumbnailnw:
    driver: bridge