// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/thumbnail.proto

/*
Package thumbnail is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package thumbnail

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_ThumbnailApiService_GetThumbnail_0(ctx context.Context, marshaler runtime.Marshaler, client ThumbnailApiServiceClient, req *http.Request, pathParams map[string]string) (ThumbnailApiService_GetThumbnailClient, runtime.ServerMetadata, error) {
	var protoReq GetThumbnailRequset
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.GetThumbnail(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterThumbnailApiServiceHandlerServer registers the http handlers for service ThumbnailApiService to "mux".
// UnaryRPC     :call ThumbnailApiServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterThumbnailApiServiceHandlerFromEndpoint instead.
func RegisterThumbnailApiServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ThumbnailApiServiceServer) error {

	mux.Handle("POST", pattern_ThumbnailApiService_GetThumbnail_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterThumbnailApiServiceHandlerFromEndpoint is same as RegisterThumbnailApiServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterThumbnailApiServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterThumbnailApiServiceHandler(ctx, mux, conn)
}

// RegisterThumbnailApiServiceHandler registers the http handlers for service ThumbnailApiService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterThumbnailApiServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterThumbnailApiServiceHandlerClient(ctx, mux, NewThumbnailApiServiceClient(conn))
}

// RegisterThumbnailApiServiceHandlerClient registers the http handlers for service ThumbnailApiService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ThumbnailApiServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ThumbnailApiServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ThumbnailApiServiceClient" to call the correct interceptors.
func RegisterThumbnailApiServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ThumbnailApiServiceClient) error {

	mux.Handle("POST", pattern_ThumbnailApiService_GetThumbnail_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/thumbnail.ThumbnailApiService/GetThumbnail", runtime.WithHTTPPathPattern("/thumbnail"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ThumbnailApiService_GetThumbnail_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ThumbnailApiService_GetThumbnail_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ThumbnailApiService_GetThumbnail_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"thumbnail"}, ""))
)

var (
	forward_ThumbnailApiService_GetThumbnail_0 = runtime.ForwardResponseStream
)
